format = """
$os\
$username\
$hostname\
$git_branch\
$git_status\
$character\
"""

command_timeout=1000

# Palettes:
#   opal: sky blue.
#   amethyst: purple.
#   ruby: red.
# To change the colors: change to the corresponding palette.

palette = "tokyo"

# Disables the blank line at the start of the prompt
add_newline = true

[palettes.tokyo]
first = "#7aa2f7"
second = "#7aa2f7"
third = "#414868"
fourth = "#414868"
fifth = "#414868"
sixth = "#414868"
seventh = "#414868"
eighth = "#414868"
error = "#C1121F"
# Text color:
black = "#0f0f14"
white = "#9699a3"
github = "#B02B10"

[palettes.opal]
first = "#38959E"
second = "#37929D"
third = "#358F9B"
fourth = "#358CA0"
fifth = "#3689A2"
sixth = "#3785A4"
seventh = "#3982A9"
eighth = "#3A7EAE"
error = "#C1121F"
# Text color:
black = "#272D37"
white = "#CBF4F8"
github = "#B02B10"

[palettes.amethyst]
first = "#6E43C4"
second = "#6A3EC0"
third = "#693CBC"
fourth = "#663AB7"
fifth = "#6238B1"
sixth = "#6037AC"
seventh = "#5D36A6"
eighth = "#5A359E"
error = "#C1121F"
# Text color:
black = "#272D37"
white = "#F2EBFF"
github = "#B02B10"

[palettes.ruby]
first = "#873739"
second = "#8B383B"
third = "#8D393C"
fourth = "#8F393D"
fifth = "#91393E"
sixth = "#92393E"
seventh = "#93393F"
eighth = "#98393F"
error = "#C1121F"
# Text color:
black = "#0f0f14"
white = "#9699a3"
github = "#450920"

[os]
format = "[](first)[$symbol]($style)[](fg:first bg:second)"
style = "bg:first fg:black"
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[username]
show_always = true
style_user = "bg:second fg:black"
style_root = "bg:second fg:red"
format = '[]($style)[](fg:second bg:third)'
disabled = false

[hostname]
ssh_only = false
format = '[ $hostname]($style)(fg:black bg:third)'
style = 'bg:third fg:black'
disabled = false

[directory]
style = "bg:third fg:black"
format = "[   $path ]($style)($style)[$read_only](fg:$read_only_style bg:fourth)[](fg:third bg:fourth)"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[directory.substitutions]
"Documents" = " "
"Downloads" = "  "
"Music" = "󰝚 "
"Pictures" = "  "
"Repos" = "󰊢 "
"Desktop" = "  "

[c]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[golang]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[python]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
python_binary = ["./venv/bin/python", "./env/Scripts/python", "python", "python3", "python2"]
format = '[$symbol($version)]($style)[ (\($virtualenv\)) ](bg:fourth fg:black)'

[conda]
symbol = " "
style = "bg:fourth fg:black"
ignore_base = false
format = '[$symbol ($environment) ]($style)'

[haskell]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[java]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[julia]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[nodejs]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[rust]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:black"
format = '[$symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:fifth fg:black"
format = '[$symbol $context ]($style)'

[git_branch]
symbol = " "
style = "bg:sixth fg:black"
format = '[$symbol $branch ]($style)'

[git_status]
format = '([\($all_status$ahead_behind\) ]($style))'
style = "bold bg:sixth fg:github"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:seventh fg:black"
format = '[  $time]($style)[](fg:seventh bg:eighth)'

[cmd_duration]
style = "bg:eighth fg:black"
format = '[  $duration ]($style)'

[character]
success_symbol = "[](fg:eighth bg:eighth)[](fg:eighth)"
error_symbol = "[](fg:eighth bg:error)[](fg:error)"

